---
http_interactions:
- request:
    method: put
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/
    body:
      encoding: UTF-8
      string: ''
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165924Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '0'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - D7EKPhJCUqWZKSXbzJFt4awV8pev8Hnv2qNs0adtnfR3k3JvSoZFl9t1ooCmOSybssajVDZhB/k=
      X-Amz-Request-Id:
      - E7YX39GDRTSD139E
      Date:
      - Fri, 16 Jul 2021 16:59:25 GMT
      Location:
      - "/some_bucket_name_one_release_yes_config"
      Server:
      - AmazonS3
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:24 GMT
- request:
    method: put
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/rex/releases/foobar/rex/release.json
    body:
      encoding: UTF-8
      string: '{"books":{"uid1":{"defaultVersion":"1.2"},"uid2":{"defaultVersion":"1.1"}}}'
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Expect:
      - 100-continue
      Content-Md5:
      - SV0iHQHQlJla2U1fH9/WPA==
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165924Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - 26789e894fe9e1a2350bab23a6605e0225d7adf54e01a875eac8143b0b160ec7
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=content-md5;expect;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '75'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - ndwpbS+Kxjpzgav/tUM7ywZ0tlvuV6AL3+pz4wdCmkir+WdWx4g2MIaKocXX2aEZ3X4i3tKGlSw=
      X-Amz-Request-Id:
      - E7YVQA5DWA501BJZ
      Date:
      - Fri, 16 Jul 2021 16:59:25 GMT
      Etag:
      - '"495d221d01d094995ad94d5f1fdfd63c"'
      Server:
      - AmazonS3
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:24 GMT
- request:
    method: put
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/rex/releases/foobar/rex/config.json
    body:
      encoding: UTF-8
      string: '{"REACT_APP_ARCHIVE_URL":"/apps/archive/101.42"}'
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Expect:
      - 100-continue
      Content-Md5:
      - xw/MUELje+OTbusEV7Egmw==
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165924Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - 59cb4b1f2af9901ecbf81dfebd51eb81d99bebdb44855205995be73e1608332a
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=content-md5;expect;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '48'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - NUjmvZPeIQO4BDbV0g6VafUxFQL/yXbmEKnP/DhekWddKfFTWujl7EJW1FLxY+zoW2h97lWW2s4=
      X-Amz-Request-Id:
      - C65E6XTZEBF3XZK1
      Date:
      - Fri, 16 Jul 2021 16:59:26 GMT
      Etag:
      - '"c70fcc5042e37be3936eeb0457b1209b"'
      Server:
      - AmazonS3
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:25 GMT
- request:
    method: get
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/?delimiter=/&encoding-type=url&prefix=rex/releases/
    body:
      encoding: UTF-8
      string: ''
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165925Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '0'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - 1zxNqHXa+e+VBdtPyRsW2NlaQ+cf/BALT7tREb1kuHbcOmA3+nzk0wFl+hnIO7f07g7Ugu/bVBw=
      X-Amz-Request-Id:
      - C657FWBS4NEJ5J7C
      Date:
      - Fri, 16 Jul 2021 16:59:26 GMT
      X-Amz-Bucket-Region:
      - us-east-1
      Content-Type:
      - application/xml
      Transfer-Encoding:
      - chunked
      Server:
      - AmazonS3
    body:
      encoding: UTF-8
      string: |-
        <?xml version="1.0" encoding="UTF-8"?>
        <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>some_bucket_name_one_release_yes_config</Name><Prefix>rex/releases/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><EncodingType>url</EncodingType><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>rex/releases/foobar/</Prefix></CommonPrefixes></ListBucketResult>
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:25 GMT
- request:
    method: get
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/rex/releases/foobar/rex/release.json
    body:
      encoding: UTF-8
      string: ''
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165925Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '0'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - hpGbP8XHYAZTd7WTaryk9bxI4h5F5wkKX7JfJBCmeiLcrTbCzFsf6ho0+9mSaixVJo7/eSpHxOc=
      X-Amz-Request-Id:
      - C659ZNZHKQ1B6ATH
      Date:
      - Fri, 16 Jul 2021 16:59:26 GMT
      Last-Modified:
      - Fri, 16 Jul 2021 16:59:25 GMT
      Etag:
      - '"495d221d01d094995ad94d5f1fdfd63c"'
      Accept-Ranges:
      - bytes
      Content-Type:
      - ''
      Server:
      - AmazonS3
      Content-Length:
      - '75'
    body:
      encoding: UTF-8
      string: '{"books":{"uid1":{"defaultVersion":"1.2"},"uid2":{"defaultVersion":"1.1"}}}'
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:25 GMT
- request:
    method: get
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/rex/releases/foobar/rex/config.json
    body:
      encoding: UTF-8
      string: ''
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165925Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '0'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - De9nHDJzBZm12v0rck8i0oczn+Aghd+KexrOAIhImt49xineSnPqbrMY+5wT+6OGvjJMMaFDZvU=
      X-Amz-Request-Id:
      - PDDNS46W1DYTQJWH
      Date:
      - Fri, 16 Jul 2021 16:59:27 GMT
      Last-Modified:
      - Fri, 16 Jul 2021 16:59:26 GMT
      Etag:
      - '"c70fcc5042e37be3936eeb0457b1209b"'
      Accept-Ranges:
      - bytes
      Content-Type:
      - ''
      Server:
      - AmazonS3
      Content-Length:
      - '48'
    body:
      encoding: UTF-8
      string: '{"REACT_APP_ARCHIVE_URL":"/apps/archive/101.42"}'
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:26 GMT
- request:
    method: get
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/?encoding-type=url&versions
    body:
      encoding: UTF-8
      string: ''
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165926Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '0'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - 10RBZs+5aXjEpt671MoQpY4l1CMwmJvkd4GW00Ky8aT/ybFc6DVzJ4InYIOruVzkdTMLzBP5Wic=
      X-Amz-Request-Id:
      - PDDGTD721X2VVGZX
      Date:
      - Fri, 16 Jul 2021 16:59:27 GMT
      Content-Type:
      - application/xml
      Transfer-Encoding:
      - chunked
      Server:
      - AmazonS3
    body:
      encoding: UTF-8
      string: |-
        <?xml version="1.0" encoding="UTF-8"?>
        <ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>some_bucket_name_one_release_yes_config</Name><Prefix></Prefix><KeyMarker></KeyMarker><VersionIdMarker></VersionIdMarker><MaxKeys>1000</MaxKeys><EncodingType>url</EncodingType><IsTruncated>false</IsTruncated><Version><Key>rex/releases/foobar/rex/config.json</Key><VersionId>null</VersionId><IsLatest>true</IsLatest><LastModified>2021-07-16T16:59:26.000Z</LastModified><ETag>&quot;c70fcc5042e37be3936eeb0457b1209b&quot;</ETag><Size>48</Size><Owner><ID>6e0b5222eaecc8fba4de9d31646cd4b222bfe0630f7eac42fcb3132bdeb18fbc</ID><DisplayName>aws-dev-sandbox</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Version><Version><Key>rex/releases/foobar/rex/release.json</Key><VersionId>null</VersionId><IsLatest>true</IsLatest><LastModified>2021-07-16T16:59:25.000Z</LastModified><ETag>&quot;495d221d01d094995ad94d5f1fdfd63c&quot;</ETag><Size>75</Size><Owner><ID>6e0b5222eaecc8fba4de9d31646cd4b222bfe0630f7eac42fcb3132bdeb18fbc</ID><DisplayName>aws-dev-sandbox</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Version></ListVersionsResult>
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:26 GMT
- request:
    method: post
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/?delete
    body:
      encoding: UTF-8
      string: |
        <Delete xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
          <Object>
            <Key>rex/releases/foobar/rex/config.json</Key>
            <VersionId>null</VersionId>
          </Object>
          <Object>
            <Key>rex/releases/foobar/rex/release.json</Key>
            <VersionId>null</VersionId>
          </Object>
        </Delete>
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Expect:
      - 100-continue
      Content-Md5:
      - mASIrmfyG5WZBNJBZNi1qA==
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165926Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - fe55194413e94f783617b863396c7c3a95fdf0ce8437f1c1e33ebe0017f8e818
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=content-md5;expect;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '280'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - 1GiUgdbdieWdNv25h6im1xBP5oiXbw7Smhjnk3ESvoUGcBnINKO5HfXpT2YhJilDnxKIp7m42y0=
      X-Amz-Request-Id:
      - PDDXSYD9PRPTK2A9
      Date:
      - Fri, 16 Jul 2021 16:59:27 GMT
      Content-Type:
      - application/xml
      Transfer-Encoding:
      - chunked
      Server:
      - AmazonS3
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |-
        <?xml version="1.0" encoding="UTF-8"?>
        <DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Deleted><Key>rex/releases/foobar/rex/release.json</Key><VersionId>null</VersionId></Deleted><Deleted><Key>rex/releases/foobar/rex/config.json</Key><VersionId>null</VersionId></Deleted></DeleteResult>
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:26 GMT
- request:
    method: delete
    uri: https://some_bucket_name_one_release_yes_config.s3.amazonaws.com/
    body:
      encoding: UTF-8
      string: ''
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.44.1 ruby/2.6.5 x86_64-darwin19 aws-sdk-s3/1.30.0
      Host:
      - some_bucket_name_one_release_yes_config.s3.amazonaws.com
      X-Amz-Date:
      - 20210716T165926Z
      X-Amz-Security-Token:
      - AWS_SESSION_TOKEN
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20210716/us-east-1/s3/aws4_request,
        SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token,
        Signature=<SignatureValue>
      Content-Length:
      - '0'
      Accept:
      - "*/*"
  response:
    status:
      code: 204
      message: No Content
    headers:
      X-Amz-Id-2:
      - MjtL2HsZlPkm/3imAJHXWpf580uKrDZcLV//DosxYS0LrmVQeBrcnYDsQCeGV/4UNkQVkkS0qTA=
      X-Amz-Request-Id:
      - FWD5M19SJMSXRGP1
      Date:
      - Fri, 16 Jul 2021 16:59:28 GMT
      Server:
      - AmazonS3
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 16 Jul 2021 16:59:27 GMT
recorded_with: VCR 4.0.0
